"""empty message

Revision ID: 67f25d056508
Revises: dca767b441a6
Create Date: 2018-07-02 17:39:52.668336

"""

# revision identifiers, used by Alembic.
revision = '67f25d056508'
down_revision = 'dca767b441a6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('baskets_items_baskets_fkey', 'baskets_items', type_='foreignkey')
    op.drop_constraint('baskets_items_items_fkey', 'baskets_items', type_='foreignkey')
    op.create_foreign_key(None, 'baskets_items', 'items', ['items'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'baskets_items', 'baskets', ['baskets'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'baskets_items', type_='foreignkey')
    op.drop_constraint(None, 'baskets_items', type_='foreignkey')
    op.create_foreign_key('baskets_items_items_fkey', 'baskets_items', 'items', ['items'], ['id'])
    op.create_foreign_key('baskets_items_baskets_fkey', 'baskets_items', 'baskets', ['baskets'], ['id'])
    # ### end Alembic commands ###
